[tox]
envlist = py310
skipsdist = True

[testenv]
deps =
    PyQt6
    requests
    sentence-transformers
    beautifulsoup4
    python-docx
    numpy
    flask
    pytest-qt
commands =
    pytest --basetemp={envtmpdir}